[package]
name = "hidg-cli"
description = "Linux USB HID Gadget emulation. Command-line tool"
version = "0.1.2"
authors = ["K. <kayo@illumium.org>"]
license = "MIT"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["USB", "Gadget", "HID", "Linux", "Input"]
edition = "2021"
publish = false

[[bin]]
name = "hidg"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
rustyline.workspace = true

[dependencies.hidg]
workspace = true
default-features = false
features = ["fromstr", "display", "phf", "keyboard", "mouse"]

[dependencies.clap]
workspace = true
features = ["derive"]
